# .readthedocs.yaml
# Tells Read the Docs how to build your project.
version: 2

# Set the version of Python and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

# Build your Sphinx documentation
sphinx:
  configuration: docs/source/conf.py

# Install your project's dependencies, including for the docs
python:
  install:
    - requirements: docs/requirements.txt